### ISSUE TITLE
stm.subset(method='polygon', polygon=path_polygon) expects points and time dimensions without checking

### ISSUE THREAD

**Issue by Simon-van-Diepen** [MotionbyLearning/stmtools#27]
It just crashes at the end

File ~/Workspace/stmtools/stm/stm.py:152, in SpaceTimeMatrix.subset(self, method, **kwargs)
    144     case other:
    145         raise NotImplementedError(
    146             "Method: {} is not implemented.".format(method)
    147         )
    148 chunks = {
    149     "points": min(
    150         self._obj.chunksizes["points"][0], data_xr_subset.points.shape[0]
    151     ),
--> 152     "time": min(self._obj.chunksizes["time"][0], data_xr_subset.time.shape[0]),
    153 }
    155 data_xr_subset = data_xr_subset.chunk(chunks)
    157 return data_xr_subset

File ~/mambaforge/envs/jupyter_dask/lib/python3.11/site-packages/xarray/core/utils.py:455, in Frozen.__getitem__(self, key)
    454 def __getitem__(self, key: K) -> V:
--> 455     return self.mapping[key]

KeyError: 'time'

**Comment by rogerkuou** [comment]
Hi @Simon-van-Diepen, may I ask if you could try [this branch](https://github.com/MotionbyLearning/stmtools/tree/27_subset_assume_space_time).

I added a regulate function to add a "time" dimension. The subset function should work after dimension regulation. E.g.:

```python
# First regulate 
stmat_regulated = stmat.regulate_dims()

# Then subset
stmat_subset =  stmat_regulated.subest(...)
```

If this works for you I will merge PR #36.

Thanks in advance!
